[project]
name = "taxonomy-refinement"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.3.3",
    "openai>=2.3.0",
    "pandas>=2.3.3",
    "pydantic>=2.12.0",
]
